<PopupAddJob>:
Label:
    text: "You pressed a button"
    size_hint: 0.6, 0.2
    pos_hint: {"x":0.2, "top":1}
TextInput:
    id: add_job
    multiline: False
    size_hint: 0.6, 0.2
    pos_hint: {"x":0.2, "y":0.5}
Button:
    text: "Close"
    on_press:add_job.focus=True
    on_press: SettingsWindow.dismiss_popup() # <<<<<<<<<< *** PROBLEM IS HERE ***
    size_hint: 0.6, 0.2
    pos_hint: {"x":0.2, "y":0.3}